sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "040731"
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucket-name: aoao-cqwm
  redis:
    host: localhost
    port: 6379
    #password: "040731"
    database: 0